source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  # pod 'Alamofire'
  # pod 'AlamofireImage'
  # pod 'IQKeyboardManagerSwift'
  # pod 'Kingfisher'
  # pod 'SDWebImage'
  # pod 'MBProgressHUD'
  # pod 'MMPopupView'
  # pod 'MJRefresh'
  # pod 'SnapKit'
  # pod 'SnapKitExtend'
  # pod 'SwiftExpand'
  # pod 'HandyJSON'
  # pod 'RxCocoa'
  # pod 'RxSwift'

  # pod ‘YYCache'
  # pod 'YYCategories'
  # pod 'YYModel'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
